import { Scenario } from '../types';

export const DEFAULT_PRESETS: Scenario[] = [
  {
    id: 'preset_normal',
    name: 'Standard Distribution Day',
    description: 'Balanced daily distribution center operations with 12,500 units and regular staffing.',
    inputs: {
      totalOrders: 2500,
      totalSkus: 850,
      totalUnits: 12500,
      avgUnitsPerOrder: 5.0,
      avgWeightPerOrderKg: 8.5,
      avgCubeM3: 0.04,
      workingShiftMins: 600,
      breakTimeMins: 60,
      workingDaysPerMonth: 22,
      isPeakSeason: false,
      isWeekend: false,
      isHoliday: false,
    },
    inboundBenchmark: {
      itemsPerPerson: 120,
      skuComplexityFactor: 1.1,
      weightFactor: 1.1,
      receivingEfficiencyPct: 92,
      dockAvailabilityPct: 95,
      expectedDelayPct: 5,
    },
    outboundBenchmark: {
      itemsPerPerson: 150,
      avgPicksPerHour: 130,
      avgLinesPerOrder: 3.2,
      waveEfficiencyPct: 92,
      pickingAccuracyPct: 99.2,
      packingEfficiencyPct: 95,
      avgWalkingDistanceFactor: 1.15,
    },
    auditBenchmark: {
      itemsAuditedPerPerson: 85,
      auditSamplingPct: 10,
      auditAccuracyPct: 99.5,
      documentationTimePerAuditMins: 2,
      reworkPct: 3,
    },
    resources: {
      availableAssociates: 28,
      availableSupervisors: 3,
      multiSkilledAssociates: 6,
      temporaryWorkers: 0,
      maxOvertimeAllowedMins: 120,
      maxWorkingHours: 12,
      maxAssociatesAllowed: 50,
      absenteeismBufferPct: 5,
      skillMatrix: {
        beginnerPct: 20,
        skilledPct: 60,
        expertPct: 20,
      },
      equipment: {
        forkliftsAvailable: 6,
        dockDoorsAvailable: 12,
        scannersAvailable: 35,
      },
    },
    financials: {
      operatorCostPerHour: 22,
      supervisorCostPerHour: 35,
      tempWorkerCostPerHour: 26,
      overtimeMultiplier: 1.5,
    },
    priorities: {
      outbound: 1,
      inbound: 2,
      audit: 3,
    },
    optimizationGoal: 'min_overtime',
  },
  {
    id: 'preset_cyber_monday',
    name: 'Cyber Monday Peak Surge',
    description: 'High volume surge (28,000 units, 5,500 orders) requiring temporary workers & overtime.',
    inputs: {
      totalOrders: 5500,
      totalSkus: 1400,
      totalUnits: 28000,
      avgUnitsPerOrder: 5.1,
      avgWeightPerOrderKg: 6.2,
      avgCubeM3: 0.035,
      workingShiftMins: 600,
      breakTimeMins: 60,
      workingDaysPerMonth: 22,
      isPeakSeason: true,
      isWeekend: false,
      isHoliday: false,
    },
    inboundBenchmark: {
      itemsPerPerson: 135,
      skuComplexityFactor: 1.2,
      weightFactor: 1.0,
      receivingEfficiencyPct: 94,
      dockAvailabilityPct: 98,
      expectedDelayPct: 8,
    },
    outboundBenchmark: {
      itemsPerPerson: 165,
      avgPicksPerHour: 145,
      avgLinesPerOrder: 3.5,
      waveEfficiencyPct: 95,
      pickingAccuracyPct: 99.4,
      packingEfficiencyPct: 96,
      avgWalkingDistanceFactor: 1.1,
    },
    auditBenchmark: {
      itemsAuditedPerPerson: 90,
      auditSamplingPct: 8,
      auditAccuracyPct: 99.6,
      documentationTimePerAuditMins: 1.5,
      reworkPct: 2.5,
    },
    resources: {
      availableAssociates: 35,
      availableSupervisors: 4,
      multiSkilledAssociates: 10,
      temporaryWorkers: 8,
      maxOvertimeAllowedMins: 120,
      maxWorkingHours: 12,
      maxAssociatesAllowed: 60,
      absenteeismBufferPct: 8,
      skillMatrix: {
        beginnerPct: 35,
        skilledPct: 50,
        expertPct: 15,
      },
      equipment: {
        forkliftsAvailable: 8,
        dockDoorsAvailable: 16,
        scannersAvailable: 50,
      },
    },
    financials: {
      operatorCostPerHour: 22,
      supervisorCostPerHour: 35,
      tempWorkerCostPerHour: 28,
      overtimeMultiplier: 1.5,
    },
    priorities: {
      outbound: 1,
      inbound: 2,
      audit: 3,
    },
    optimizationGoal: 'balanced_sla',
  },
  {
    id: 'preset_heavy_inbound',
    name: 'Heavy Restock / Receiving Day',
    description: 'Inbound-heavy workload with large SKU replenishment and container offloading.',
    inputs: {
      totalOrders: 1200,
      totalSkus: 2100,
      totalUnits: 18000,
      avgUnitsPerOrder: 15.0,
      avgWeightPerOrderKg: 18.0,
      avgCubeM3: 0.08,
      workingShiftMins: 600,
      breakTimeMins: 60,
      workingDaysPerMonth: 22,
      isPeakSeason: false,
      isWeekend: false,
      isHoliday: false,
    },
    inboundBenchmark: {
      itemsPerPerson: 100,
      skuComplexityFactor: 1.5,
      weightFactor: 1.4,
      receivingEfficiencyPct: 88,
      dockAvailabilityPct: 90,
      expectedDelayPct: 10,
    },
    outboundBenchmark: {
      itemsPerPerson: 140,
      avgPicksPerHour: 120,
      avgLinesPerOrder: 2.5,
      waveEfficiencyPct: 90,
      pickingAccuracyPct: 99.0,
      packingEfficiencyPct: 92,
      avgWalkingDistanceFactor: 1.25,
    },
    auditBenchmark: {
      itemsAuditedPerPerson: 75,
      auditSamplingPct: 15,
      auditAccuracyPct: 99.2,
      documentationTimePerAuditMins: 2.5,
      reworkPct: 4.0,
    },
    resources: {
      availableAssociates: 30,
      availableSupervisors: 3,
      multiSkilledAssociates: 8,
      temporaryWorkers: 2,
      maxOvertimeAllowedMins: 120,
      maxWorkingHours: 12,
      maxAssociatesAllowed: 50,
      absenteeismBufferPct: 5,
      skillMatrix: {
        beginnerPct: 15,
        skilledPct: 65,
        expertPct: 20,
      },
      equipment: {
        forkliftsAvailable: 7,
        dockDoorsAvailable: 10,
        scannersAvailable: 40,
      },
    },
    financials: {
      operatorCostPerHour: 22,
      supervisorCostPerHour: 35,
      tempWorkerCostPerHour: 26,
      overtimeMultiplier: 1.5,
    },
    priorities: {
      inbound: 1,
      outbound: 2,
      audit: 3,
    },
    optimizationGoal: 'max_utilization',
  },
];
